workflows:
  xcode_build:
    name: Build iOS App Without CocoaPods
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"  # Replace with your project name
        SCHEME: "ShakeFlashlightWidgetApp"        # Replace with your scheme name
      xcode: latest                               # Use the latest Xcode version available
    scripts:
      - name: Clean and prepare the project
        script: |
          # Clean previous builds and derived data
          rm -rf /Users/builder/clone/DerivedData
          xcodebuild clean -project ${PROJECT_NAME}.xcodeproj
      - name: Build the app for iOS Simulator
        script: |
          # Build the app targeting the iOS Simulator with explicit derived data path
          xcodebuild \
            -project ${PROJECT_NAME}.xcodeproj \
            -scheme ${SCHEME} \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -derivedDataPath /Users/builder/clone/DerivedData \
            clean build | tee build.log
      - name: Check DerivedData contents
        script: |
          # List contents of DerivedData to confirm .app creation
          if [ -d "/Users/builder/clone/DerivedData" ]; then
            echo "DerivedData directory contents:"
            find /Users/builder/clone/DerivedData -name "*.app" || echo "No .app file found"
          else
            echo "DerivedData directory does not exist."
            exit 1
          fi
    artifacts:
      - build.log                                  # Save build logs for debugging
      - /Users/builder/clone/DerivedData/Build/Products/Debug-iphonesimulator/*.app
