version: 2  # Codemagic YAML version

workflows:
  build-and-deploy:
    platform:
      ios:
        build:
          - flutter clean
          - flutter pub get
          - flutter build ios --release --no-codesign
        deploy:
          - script: |
              gem install fastlane
              cd ios
              fastlane ios beta
