version: 2  # Codemagic YAML version

workflows:
  build-and-deploy:
    name: Build and Deploy with Xcode 15 to TestFlight
    ios:
      # Steps to run for the iOS platform
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
      - script: |
          gem install fastlane
          cd ios
          fastlane ios beta
