workflows:
  ios_altstore_unsigned_build:
    name: Build Unsigned iOS App for AltStore
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"
        SCHEME: "ShakeFlashlightWidgetApp"
        PROJECT_PATH: "ShakeFlashlightWidgetApp.xcodeproj"
    scripts:
      - name: Set Xcode version
        script: |
          sudo xcode-select -s /Applications/Xcode-16.2.app/Contents/Developer
          xcodebuild -version
      - name: Debug project directory
        script: |
          echo "Checking current directory and files:"
          ls -R
      - name: Check project file
        script: |
          if [ ! -f $PROJECT_PATH/project.pbxproj ]; then
            echo "Error: Project file $PROJECT_PATH not found."
            exit 1
          fi
      - name: Validate plist files
        script: |
          plutil -lint ShakeFlashlightWidgetApp/Info.plist
          plutil -lint exportOptions.plist
      - name: Clean the project
        script: |
          xcodebuild clean -project $PROJECT_PATH
      - name: Build the app
        script: |
          xcodebuild \
            -project $PROJECT_PATH \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -derivedData
