workflows:
  ios_altstore_unsigned_build:
    name: Build Unsigned iOS App for AltStore
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"
        SCHEME: "ShakeFlashlightWidgetApp"
        PROJECT_PATH: "ShakeFlashlightWidgetApp.xcodeproj"
    scripts:
      - name: Check project file
        script: |
          if [ ! -f $PROJECT_PATH/project.pbxproj ]; then
            echo "Error: Project file $PROJECT_PATH not found."
            exit 1
          fi
      - name: Clean the project
        script: |
          xcodebuild clean -project $PROJECT_PATH || echo "Warning: Clean failed, continuing build."
      - name: Build the app
        script: |
          xcodebuild \
            -project $PROJECT_PATH \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath $HOME/DerivedData \
            build || { echo "Error: Build failed."; exit 1; }
      - name: Archive the app
        script: |
          xcodebuild \
            -project $PROJECT_PATH \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/${PROJECT_NAME}.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive || { echo "Error: Archive failed."; exit 1; }
      - name: Remove app name from development assets
        script: |
          plutil -remove ':assets:developmentAssets:0:appName' $HOME/${PROJECT_NAME}.xcarchive/Info.plist || echo "No app name found under development assets."
      - name: List archive contents
        script: |
          echo "Listing contents of $HOME/${PROJECT_NAME}.xcarchive:"
          ls $HOME/${PROJECT_NAME}.xcarchive
      - name: Inspect archive contents
        script: |
          echo "Inspecting contents of $HOME/${PROJECT_NAME}.xcarchive:"
          find $HOME/${PROJECT_NAME}.xcarchive -type f
      - name: Export the unsigned .ipa file
        script: |
          if [ ! -d $HOME/${PROJECT_NAME}.xcarchive ]; then
            echo "Error: Archive not found at $HOME/${PROJECT_NAME}.xcarchive."
            exit 1
          fi
          xcodebuild -exportArchive \
            -archivePath $HOME/${PROJECT_NAME}.xcarchive \
            -exportOptionsPlist ./exportOptions.plist \
            -exportPath $HOME/ExportedProducts || { echo "Error: Export failed."; exit 1; }
    artifacts:
      - $HOME/ExportedProducts/*.ipa
