workflows:
  xcode_build:
    name: Build iOS App Without CocoaPods
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"  # Replace with your project name
        SCHEME: "ShakeFlashlightWidgetApp"        # Replace with your scheme name
      xcode: latest                               # Use the latest Xcode version available
    scripts:
      - name: Clean and prepare the project
        script: |
          # Clean previous builds and derived data
          rm -rf $HOME/Library/Developer/Xcode/DerivedData
          xcodebuild clean -project ${PROJECT_NAME}.xcodeproj
      - name: Build the app for iOS Simulator
        script: |
          # Build the app targeting the iOS Simulator
          xcodebuild \
            -project ${PROJECT_NAME}.xcodeproj \
            -scheme ${SCHEME} \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean build | tee build.log
      - name: Verify build output
        script: |
          # Ensure the app build output exists
          if [ ! -d "$HOME/Library/Developer/Xcode/DerivedData" ]; then
            echo "Build output not found! Check for errors in build.log."
            exit 1
          fi
    artifacts:
      - build.log                                  # Save build logs for debugging
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
