scripts:
  - name: Build the App
    script: |
      xcodebuild -project ShakeFlashlightWidgetApp.xcodeproj \
                  -scheme ShakeFlashlightWidgetApp \
                  -sdk iphonesimulator \
                  -configuration Debug clean build
