version: 2  # Codemagic YAML version (this is not part of workflows but for the whole file)

workflows:
  build-and-deploy:
    name: Build and Deploy with Xcode 15 to TestFlight
    platform:
      ios:
        build:
          - flutter clean
          - flutter pub get
          - flutter build ios --release --no-codesign
        deploy:
          - script: |
              # Install fastlane
              gem install fastlane
              cd ios
              # Use fastlane to upload to TestFlight
              fastlane ios beta

    environment:
      xcode: "15.0"  # Xcode version to use
      flutter: stable  # Flutter version to use

    dependencies:
      pre_cache:
        - flutter
        - cocoapods

    tests:
      post-build:
        - flutter test
