workflows:
  version: 2.0  # Define the version correctly as a string

  build-and-deploy:
    name: Build and Deploy with Xcode 15 to TestFlight
    platform:
      ios:
        # Build settings specific for Xcode 15
        build:
          - flutter clean
          - flutter pub get
          - flutter build ios --release --no-codesign
        # Deploy commands to TestFlight using fastlane
        deploy:
          - script: |
              # Install fastlane
              gem install fastlane
              cd ios
              # Use fastlane to upload to TestFlight
              fastlane ios beta

    # Environment to use Xcode 15
    environment:
      xcode: "15.0"  # Ensure to use a string format for version numbers in some cases
      flutter: stable  # Adjust this if you want a specific Flutter version

    # Dependencies to pre-cache for faster builds
    dependencies:
      pre_cache:
        - flutter
        - cocoapods

    # Optional: Run tests after building the app
    tests:
      post-build:
        - flutter test
