workflows:
  ios_altstore_unsigned_build:
    name: Build Unsigned iOS App for AltStore
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"
        SCHEME: "ShakeFlashlightWidgetApp"
        PROJECT_PATH: "ShakeFlashlightWidgetApp.xcodeproj"
    scripts:
      - name: Set Xcode version
        script: |
          sudo xcode-select -s $(xcode-select -p)
          xcodebuild -version
      - name: Debug project directory
        script: |
          echo "Checking current directory and files:"
          ls -R
      - name: Check project file
        script: |
          if [ ! -f $PROJECT_PATH/project.pbxproj ]; then
            echo "Error: Project file $PROJECT_PATH not found."
            exit 1
          fi
      - name: Validate plist files
        script: |
          plutil -lint ShakeFlashlight/Info.plist
          plutil -lint exportOptions.plist
      - name: Clear Derived Data
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Clean the project
        script: |
          xcodebuild clean -project $PROJECT_PATH
      - name: Build the app
        script: |
          xcodebuild \
            -project $PROJECT_PATH \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath $CM_BUILD_DIR/DerivedData \
            DEVELOPMENT_TEAM="1234567890" \ # Replace with a dummy or valid Team ID
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build || { echo "Error: Build failed."; exit 1; }
      - name: Archive the app
        script: |
          xcodebuild \
            -project $PROJECT_PATH \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive \
            DEVELOPMENT_TEAM="1234567890" \ # Replace with a dummy or valid Team ID
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive || { echo "Error: Archive failed."; exit 1; }
      - name: Export the unsigned .ipa file
        script: |
          mkdir -p $CM_BUILD_DIR/ExportedProducts
          if [ ! -d $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive ]; then
            echo "Error: Archive not found at $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive."
            exit 1
          fi
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ExportedProducts \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO || { echo "Error: Export failed."; exit 1; }
    artifacts:
      - $CM_BUILD_DIR/ExportedProducts/*.ipa
