workflows:
  ios_altstore_unsigned_build:
    name: Build Unsigned iOS App for AltStore
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"
        SCHEME: "ShakeFlashlightWidgetApp"
      xcode: latest
    scripts:
      - name: Clean the project
        script: |
          xcodebuild clean -project ${PROJECT_NAME}.xcodeproj
      - name: Archive the app
        script: |
          xcodebuild \
            -project ${PROJECT_NAME}.xcodeproj \
            -scheme ${SCHEME} \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
      - name: Export the unsigned .ipa file
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/${PROJECT_NAME}.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ExportedProducts
    artifacts:
      - $CM_BUILD_DIR/ExportedProducts/*.ipa
