workflows:
  version: 2.0

  build-and-deploy:
    name: Build and Deploy with Xcode 15
    platform:
      ios:
        # Build settings specific for Xcode 15
        build:
          - flutter clean
          - flutter pub get
          - flutter build ios --release --no-codesign
        # Deploy commands (if you need any deployment, like Firebase or TestFlight)
        deploy:
          - script: |
              echo "Deploying to Firebase or another platform"
              # Add your deployment commands here

    # Environment to use Xcode 15
    environment:
      xcode: 15.0
      flutter: stable # Adjust this if you want a specific Flutter version

    # Dependencies to pre-cache for faster builds
    dependencies:
      pre_cache:
        - flutter
        - cocoapods

    # Optional: Run tests after building the app
    tests:
      post-build:
        - flutter test
