workflows:
  free_build:
    name: Free Account iOS Build
    environment:
      vars:
        # Set any required environment variables here
        PROJECT_NAME: "ShakeFlashlightWidgetApp"
        SCHEME: "ShakeFlashlightWidgetApp"
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build for iOS Simulator
        script: |
          xcodebuild \
            -workspace ${PROJECT_NAME}.xcworkspace \
            -scheme ${SCHEME} \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean build | tee build.log
    artifacts:
      - build.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
