workflows:
  xcode_build:
    name: Build iOS App Without CocoaPods
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp"  # Replace with your project name
        SCHEME: "ShakeFlashlightWidgetApp"        # Replace with your scheme name
      xcode: latest                               # Use the latest Xcode version available
    scripts:
      - name: Clean and prepare the project
        script: |
          # Clean previous builds and derived data
          rm -rf $CM_BUILD_DIR/DerivedData
          xcodebuild clean -project ${PROJECT_NAME}.xcodeproj
      - name: Build the app for iOS Simulator
        script: |
          # Build the app targeting the iOS Simulator with explicit derived data path
          xcodebuild \
            -project ${PROJECT_NAME}.xcodeproj \
            -scheme ${SCHEME} \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -derivedDataPath $CM_BUILD_DIR/DerivedData \
            clean build | tee build.log
      - name: Verify DerivedData contents
        script: |
          # Check if the DerivedData directory contains the expected build output
          if [ -d "$CM_BUILD_DIR/DerivedData" ]; then
            echo "DerivedData directory found:"
            ls -R $CM_BUILD_DIR/DerivedData
          else
            echo "DerivedData directory is missing! Check build log for issues."
            exit 1
          fi
    artifacts:
      - build.log                                  # Save build logs for debugging
      - $CM_BUILD_DIR/DerivedData/Build/Products/Debug-iphonesimulator/*.app
