
workflows:
  xcode_build:
    name: iOS Build
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build the project
        script: |
          xcodebuild -workspace ShakeFlashlightWidgetApp.xcworkspace -scheme ShakeFlashlight -sdk iphoneos -configuration Release clean build
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
