workflows:
  xcode_build:
    name: Build iOS App
    environment:
      vars:
        PROJECT_NAME: "ShakeFlashlightWidgetApp" # Replace with your actual project name
        SCHEME: "ShakeFlashlightWidgetApp"       # Replace with your scheme name
      xcode: latest                              # Use the latest Xcode version available
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build the app for iOS Simulator
        script: |
          xcodebuild \
            -workspace ${PROJECT_NAME}.xcworkspace \
            -scheme ${SCHEME} \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean build | tee build.log
    artifacts:
      - build.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphonesimulator/*.app
