workflows:
  shake2:
    name: Shake2 iOS Build
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Upgrade Ruby
        script: |
          rbenv install 3.1.2 --skip-existing
          rbenv global 3.1.2
      - name: Ensure CocoaPods is up-to-date
        script: |
          gem update --system
          gem install cocoapods --no-document
          pod repo update
      - name: Install dependencies
        script: |
          pod install
      - name: Build the app
        script: |
          xcodebuild -workspace ShakeFlashlightWidgetApp.xcworkspace \
                      -scheme ShakeFlashlight \
                      -sdk iphoneos \
                      -configuration Release clean build
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
