platform :ios, '14.0' # 

target 'ShakeFlashlightWidgetApp' do
  use_frameworks! # CocoaPods dynamic framework usage

  # Add dependencies here
  pod 'Alamofire', '~> 5.6' # Example dependency
  pod 'SwiftyJSON', '~> 5.0' # Example dependency
end
